trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: ChocolateyInstaller@0
    displayName: 'Install Qt6 Base Dev'
    inputs:
      packageName: 'qt6-base-dev'
      arguments: '--yes'
  
  - task: ChocolateyInstaller@0
    displayName: 'Install VTK (or vtklib)'
    inputs:
      packageName: 'vtk'
      arguments: '--pre --yes'

  - powershell: |
      Write-Host 'Importing Chocolatey environment helpers...'
      Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
      RefreshEnv
    displayName: 'Refresh environment variables'
  
  - task: CMake@1
    displayName: 'Configure project'
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)'
      generator: 'MinGW Makefiles'
      cmakeArgs: '-DCMAKE_BUILD_TYPE=Release'
      options: '-G "MinGW Makefiles"'
  
  - task: CMake@1
    displayName: 'Build project'
    inputs:
      workingDirectory: '$(Build.SourcesDirectory)'
      command: 'build'
      arguments: '--config Release -- /m'
  
  - script: |
      echo "Tests or post-build steps здесь"
      # например: ctest -C Release
    displayName: 'Run tests/post-build'
