# .github/workflows/build-windows.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt6
        run: |
          choco install qt6-base-dev --yes
        shell: pwsh

      - name: Install VTK (if available)
        run: |
          choco install vtk --pre --yes
        shell: pwsh

      - name: Refresh environment variables
        run: |
          Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          RefreshEnv
        shell: pwsh

      - name: Configure with CMake
        run: |
          cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Build with CMake
        run: |
          cmake --build build --config Release -- -j
        shell: bash

      - name: Run tests (optional)
        run: |
          cmake --build build --target run_tests
        shell: bash
